### ISSUE TITLE
Summarize what is happened when callee function is panicked

### ISSUE THREAD

**Issue by loloicci** [line/cosmwasm#211]
Now there is no information in this repository on what is happened when a callee function panics.

This issue's aims are

- [ ] make contracts to test and reproduce callee function panics
- [ ] summarize the information what is caused

The following are other issues' scope

- Discuss whether it is desirable behavior
- Add documents of the behavior
- Add tests for it

**Comment by da1suk8** [comment]
When an error occurred on the dynamic_callee side, the error occurred on the wasmer side, and the error content was wrapped and returned.

**instantiate**, **execute**, **migrate**, **query** is same [error point](https://github.com/line/cosmwasm/blob/c546d499aac079a2f36f6c1064254a51ecf562e2/packages/vm/src/environment.rs#L211).
 [Here](https://github.com/line/cosmwasm/blob/c546d499aac079a2f36f6c1064254a51ecf562e2/packages/vm/src/environment.rs#L208) it is running in wasmer.
 
 Since the error wrapping contained the words "Unknown error," it may be a reasonable change to the appropriate text.

**Comment by loloicci** [comment]
Nice work!
